package alsender.earthworks.main.registry;


import alsender.earthworks.block.*;
import alsender.earthworks.item.BlockItemPlanksVert;
import alsender.earthworks.item.BlockItemWoodShingle;
import net.minecraft.block.*;
import net.minecraft.block.material.Material;
import net.minecraft.item.BlockItem;
import net.minecraft.item.Item;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.registries.IForgeRegistry;

import java.lang.reflect.Field;
import java.util.ArrayList;
import java.util.List;

/**
 * Created by alsender on 12/12/16.
 */
@Mod.EventBusSubscriber
public class BlockRegistry {

    public static Block adobe;
    public static Block chalk;
    public static Block cinder;
    public static Block cob;
    public static Block concrete;
    public static Block cordwood;
    public static Block dry_stone;
    public static Block GRAVEL_GABION;
    public static Block SAND_GABION;
    public static Block DIRT_GABION;

    public static Block mud;
    public static Block mud_bottom;
    public static Block oak_planks_vert;
    public static Block birch_planks_vert;
    public static Block jungle_planks_vert;
    public static Block spruce_planks_vert;
    public static Block acacia_planks_vert;
    public static Block dark_oak_planks_vert;

    public static Block plaster;
    public static Block rammed_earth;
    public static Block block_reed;
    public static Block slate;
    public static Block block_slate_green;
    public static Block block_slate_purple;
    public static Block block_slate_slab;
    public static Block green_slate_slab;
    public static Block slate_slab_purple;
    public static Block slate_shingle;
    public static Block block_slate_shingle_verte;
    public static Block block_slate_shingle_purple;
    public static Block block_slate_tile;
    public static Block block_slate_tile_verte;
    public static Block block_slate_tile_purple;
    public static Block block_thatch;
    public static Block block_timber_oak;
    public static Block block_timber_birch;
    public static Block block_timber_spruce;
    public static Block block_timber_jungle;
    public static Block block_timber_acacia;
    public static Block block_timber_dark_oak;
    public static Block block_wattle;
    public static Block block_wicker;
    public static Block oak_wood_shingle;
    public static Block birch_wood_shingle;
    public static Block jungle_wood_shingle;
    public static Block spruce_wood_shingle;
    public static Block acacia_wood_shingle;
    public static Block dark_oak_wood_shingle;

    public static Block fence_planks_vert0;
    public static Block fence_planks_vert1;
    public static Block fence_planks_vert2;
    public static Block fence_planks_vert3;
    public static Block fence_planks_vert4;
    public static Block fence_planks_vert5;

    public static Block slab_adobe;
    public static Block slab_chalk;
    public static Block slab_cinder;
    public static Block slab_cob;
    public static Block slab_concrete;
    public static Block slab_cordwood;
    public static Block slab_dry_stone;
    public static Block slab_gabion0;
    public static Block slab_gabion1;
    public static Block slab_gabion2;
    public static Block slab_mud;
    public static Block vertical_oak_slab;
    public static Block slab_planks_vert1;
    public static Block slab_planks_vert2;
    public static Block slab_planks_vert3;
    public static Block slab_planks_vert4;
    public static Block slab_planks_vert5;
    public static Block plaster_slab;
    public static Block slab_rammed_earth;
    public static Block slab_reed;
    public static Block slab_slate;
    public static Block slab_slate_green;
    public static Block slab_slate_purple;
    public static Block slab_slate_slab;
    public static Block slab_slate_slab_green;
    public static Block slab_slate_slab_purple;
    public static Block slab_slate_shingle;
    public static Block slab_slate_shingle_verte;
    public static Block slab_slate_shingle_purple;
    public static Block slab_slate_tile;
    public static Block slab_slate_tile_verte;
    public static Block slab_slate_tile_purple;
    public static Block slab_thatch;
    public static Block slab_timber_oak;
    public static Block slab_timber_birch;
    public static Block slab_timber_spruce;
    public static Block slab_timber_jungle;
    public static Block slab_timber_acacia;
    public static Block slab_timber_dark_oak;
    public static Block slab_wattle;
    public static Block slab_wicker;
    public static Block slab_wood_shingle_oak;
    public static Block slab_wood_shingle_spruce;
    public static Block slab_wood_shingle_birch;
    public static Block slab_wood_shingle_jungle;
    public static Block slab_wood_shingle_acacia;
    public static Block slab_wood_shingle_dark_oak;

    public static Block
            stair_adobe;
    public static Block stair_chalk;
    public static Block stair_cinder;
    public static Block stair_cob;
    public static Block stair_concrete;
    public static Block stair_cordwood;
    public static Block stair_dry_stone;
    public static Block stair_gabion0;
    public static Block stair_gabion1;
    public static Block stair_gabion2;
    public static Block stair_mud;
    public static Block stair_planks_vert0;
    public static Block stair_planks_vert1;
    public static Block stair_planks_vert2;
    public static Block stair_planks_vert3;
    public static Block stair_planks_vert4;
    public static Block stair_planks_vert5;
    public static Block stair_plaster;
    public static Block stair_rammed_earth;
    public static Block stair_reed;
    public static Block stair_slate;
    public static Block stair_slate_green;
    public static Block stair_slate_purple;
    public static Block stair_slate_slab;
    public static Block stair_slate_slab_green;
    public static Block stair_slate_slab_purple;
    public static Block stair_slate_shingle;
    public static Block stair_slate_shingle_verte;
    public static Block stair_slate_shingle_purple;
    public static Block stair_slate_tile;
    public static Block stair_slate_tile_verte;
    public static Block stair_slate_tile_purple;
    public static Block stair_thatch;
    public static Block stair_timber_oak;
    public static Block stair_timber_birch;
    public static Block stair_timber_spruce;
    public static Block stair_timber_jungle;
    public static Block stair_timber_acacia;
    public static Block stair_timber_dark_oak;
    public static Block stair_wattle;
    public static Block stair_wicker;
    public static Block stair_wood_shingle_oak;
    public static Block stair_wood_shingle_spruce;
    public static Block stair_wood_shingle_birch;
    public static Block stair_wood_shingle_jungle;
    public static Block stair_wood_shingle_acacia;
    public static Block stair_wood_shingle_dark_oak;

    public static Block wall_adobe;
    public static Block wall_chalk;
    public static Block wall_cinder;
    public static Block wall_cob;
    public static Block wall_concrete;
    public static Block wall_cordwood;
    public static Block wall_dry_stone;
    public static Block wall_gabion0;
    public static Block wall_gabion1;
    public static Block wall_gabion2;
    public static Block wall_mud;
    public static Block wall_plaster;
    public static Block wall_rammed_earth;
    public static Block wall_reed;
    public static Block wall_slate;
    public static Block wall_slate_green;
    public static Block wall_slate_purple;
    public static Block wall_slate_slab;
    public static Block wall_slate_slab_green;
    public static Block wall_slate_slab_purple;
    public static Block wall_slate_shingle;
    public static Block wall_slate_shingle_verte;
    public static Block wall_slate_shingle_purple;
    public static Block wall_slate_tile;
    public static Block wall_slate_tile_verte;
    public static Block wall_slate_tile_purple;
    public static Block wall_thatch;
    public static Block wall_timber_oak;
    public static Block wall_timber_birch;
    public static Block wall_timber_spruce;
    public static Block wall_timber_jungle;
    public static Block wall_timber_acacia;
    public static Block wall_timber_dark_oak;
    public static Block wall_wattle;
    public static Block wall_wicker;
    public static Block wall_wood_shingle_oak;
    public static Block wall_wood_shingle_spruce;
    public static Block wall_wood_shingle_birch;
    public static Block wall_wood_shingle_jungle;
    public static Block wall_wood_shingle_acacia;
    public static Block wall_wood_shingle_dark_oak;

    public static SlabBlock doubleslab_adobe;
    public static SlabBlock doubleslab_chalk;
    public static SlabBlock doubleslab_cinder;
    public static SlabBlock doubleslab_cob;
    public static SlabBlock doubleslab_concrete;
    public static SlabBlock doubleslab_cordwood;
    public static SlabBlock doubleslab_dry_stone;
    public static SlabBlock doubleslab_gabion0;
    public static SlabBlock doubleslab_gabion1;
    public static SlabBlock doubleslab_gabion2;
    public static SlabBlock doubleslab_mud;
    public static SlabBlock doubleslab_planks_vert0;
    public static SlabBlock doubleslab_planks_vert1;
    public static SlabBlock doubleslab_planks_vert2;
    public static SlabBlock doubleslab_planks_vert3;
    public static SlabBlock doubleslab_planks_vert4;
    public static SlabBlock doubleslab_planks_vert5;
    public static SlabBlock doubleslab_plaster;
    public static SlabBlock doubleslab_rammed_earth;
    public static SlabBlock doubleslab_reed;
    public static SlabBlock doubleslab_slate;
    public static SlabBlock doubleslab_slate_green;
    public static SlabBlock doubleslab_slate_purple;
    public static SlabBlock doubleslab_slate_slab;
    public static SlabBlock doubleslab_slate_slab_green;
    public static SlabBlock doubleslab_slate_slab_purple;
    public static SlabBlock doubleslab_slate_shingle;
    public static SlabBlock doubleslab_slate_shingle_verte;
    public static SlabBlock doubleslab_slate_shingle_purple;
    public static SlabBlock doubleslab_slate_tile;
    public static SlabBlock doubleslab_slate_tile_verte;
    public static SlabBlock doubleslab_slate_tile_purple;
    public static SlabBlock doubleslab_thatch;
    public static SlabBlock doubleslab_timber_oak;
    public static SlabBlock doubleslab_timber_birch;
    public static SlabBlock doubleslab_timber_spruce;
    public static SlabBlock doubleslab_timber_jungle;
    public static SlabBlock doubleslab_timber_acacia;
    public static SlabBlock doubleslab_timber_dark_oak;
    public static SlabBlock doubleslab_wattle;
    public static SlabBlock doubleslab_wicker;
    public static SlabBlock doubleslab_wood_shingle_oak;
    public static SlabBlock doubleslab_wood_shingle_spruce;
    public static SlabBlock doubleslab_wood_shingle_birch;
    public static SlabBlock doubleslab_wood_shingle_jungle;
    public static SlabBlock doubleslab_wood_shingle_acacia;
    public static SlabBlock doubleslab_wood_shingle_dark_oak;

    public static void initBlocks(RegistryEvent.Register<Block> event) {
        IForgeRegistry<Block> r = event.getRegistry();
        adobe = new Block(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).hardnessAndResistance(2.0F, 3.3F));
        chalk = new Block(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).hardnessAndResistance(1.0F, 2.5F));
        cinder = new Block(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).hardnessAndResistance(1.5F, 5.83F));
        cob = new Block(Block.Properties.create(Material.EARTH).sound(SoundType.GROUND).hardnessAndResistance(1.0F, 3.0F));
        concrete = new Block(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).hardnessAndResistance(2.0F, 10.0F));
        cordwood = new ModBlockFacing(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).hardnessAndResistance(1.5F, 2.83F));
        dry_stone = new Block(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).hardnessAndResistance(2.0F, 1333.3F));
        GRAVEL_GABION = new FallingBlock(AbstractBlock.Properties.create(Material.ROCK).sound(SoundType.GROUND).hardnessAndResistance(1, 1));
        SAND_GABION = new FallingBlock(AbstractBlock.Properties.create(Material.ROCK).sound(SoundType.GROUND).hardnessAndResistance(1, 1));
        DIRT_GABION = new FallingBlock(AbstractBlock.Properties.create(Material.ROCK).sound(SoundType.GROUND).hardnessAndResistance(1, 1));
        mud = new Block_Mud(AbstractBlock.Properties.create(Material.CLAY).sound(SoundType.SLIME).hardnessAndResistance(0.6F, 1.0F));
        mud_bottom = new Block_Mud_Bottom(r, "block_mud_bottom");
        plaster = new ModBlock(Material.ROCK, SoundType.STONE, 2.0F, 7.5F);
        rammed_earth = new ModBlock(Material.EARTH, SoundType.STONE, 2.0F, 10.0F);
        slate = new ModBlock(Material.ROCK, SoundType.STONE, 1.5F, 10.0F);
        block_slate_green = new ModBlock(Material.ROCK, SoundType.STONE, 1.5F, 10.0F);
        block_slate_purple = new ModBlock(Material.ROCK, SoundType.STONE, 1.5F, 10.0F);
        block_slate_slab = new ModBlock(Material.ROCK, SoundType.STONE, 1.5F, 10.0F);
        green_slate_slab = new ModBlock(Material.ROCK, SoundType.STONE, 1.5F, 10.0F);
        slate_slab_purple = new ModBlock(Material.ROCK, SoundType.STONE, 1.5F, 10.0F);
        slate_shingle = new ModBlockFacing(AbstractBlock.Properties.create(Material.ROCK).sound(SoundType.STONE).hardnessAndResistance(1.2F, 10.0F));
        block_slate_shingle_verte = new ModBlockFacing(AbstractBlock.Properties.create(Material.ROCK).sound(SoundType.STONE).hardnessAndResistance(1.2F, 10.0F));
        block_slate_shingle_purple = new ModBlockFacing(AbstractBlock.Properties.create(Material.ROCK).sound(SoundType.STONE).hardnessAndResistance(1.2F, 10.0F));
        block_slate_tile = new ModBlock(Material.ROCK, SoundType.STONE, 1.2F, 10.0F);
        block_slate_tile_verte = new ModBlock(Material.ROCK, SoundType.STONE, 1.2F, 10.0F);
        block_slate_tile_purple = new ModBlock(Material.ROCK, SoundType.STONE, 1.2F, 10.0F);
        block_timber_oak = new RotatedPillarBlock(AbstractBlock.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(2.0F, 3.33F));
        block_timber_birch = new RotatedPillarBlock(AbstractBlock.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(2.0F, 3.33F));
        block_timber_spruce = new RotatedPillarBlock(AbstractBlock.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(2.0F, 3.33F));
        block_timber_jungle = new RotatedPillarBlock(AbstractBlock.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(2.0F, 3.33F));
        block_timber_acacia = new RotatedPillarBlock(AbstractBlock.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(2.0F, 3.33F));
        block_timber_dark_oak = new RotatedPillarBlock(AbstractBlock.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(2.0F, 3.33F));
        block_wattle = new ModBlock(Material.ROCK, SoundType.STONE, 1.5F, 8.33F);
        block_wicker = new ModBlock(Material.WOOD, SoundType.CLOTH, 0.8F, 1.0F);
        oak_wood_shingle = new Block_Wood_Shingle(Material.WOOD, SoundType.WOOD, 2.0F, 3.33F);
        birch_wood_shingle = new Block_Wood_Shingle(Material.WOOD, SoundType.WOOD, 2.0F, 3.33F);
        jungle_wood_shingle = new Block_Wood_Shingle(Material.WOOD, SoundType.WOOD, 2.0F, 3.33F);
        spruce_wood_shingle = new Block_Wood_Shingle(Material.WOOD, SoundType.WOOD, 2.0F, 3.33F);
        acacia_wood_shingle = new Block_Wood_Shingle(Material.WOOD, SoundType.WOOD, 2.0F, 3.33F);
        dark_oak_wood_shingle = new Block_Wood_Shingle(Material.WOOD, SoundType.WOOD, 2.0F, 3.33F);


        oak_planks_vert = new Block_Planks_Vert(Material.WOOD, SoundType.WOOD, 2.0F, 3.33F);
        birch_planks_vert = new Block_Planks_Vert(Material.WOOD, SoundType.WOOD, 2.0F, 3.33F);
        jungle_planks_vert = new Block_Planks_Vert(Material.WOOD, SoundType.WOOD, 2.0F, 3.33F);
        spruce_planks_vert = new Block_Planks_Vert(Material.WOOD, SoundType.WOOD, 2.0F, 3.33F);
        acacia_planks_vert = new Block_Planks_Vert(Material.WOOD, SoundType.WOOD, 2.0F, 3.33F);
        dark_oak_planks_vert = new Block_Planks_Vert(Material.WOOD, SoundType.WOOD, 2.0F, 3.33F);

        // OreDictionary.registerOre( oak_planks_vert);

//      block_chalk_dust = new Block_ChalkDust();

        fence_planks_vert0 = new FenceBlock(AbstractBlock.Properties.from(Blocks.OAK_PLANKS));
        fence_planks_vert1 = new FenceBlock(r, "fence_planks_vert_spruce");
        fence_planks_vert2 = new FenceBlock(r, "fence_planks_vert_birch");
        fence_planks_vert3 = new FenceBlock(r, "fence_planks_vert_jungle");
        fence_planks_vert4 = new FenceBlock(r, "fence_planks_vert_acacia");
        fence_planks_vert5 = new FenceBlock(r, "fence_planks_vert_dark_oak");


        slab_adobe = new SlabBlock(Block.Properties.from(adobe));
        slab_chalk = new SlabBlock(Block.Properties.from(chalk));
        slab_cinder = new SlabBlock(Block.Properties.from(cinder));
        slab_cob = new SlabBlock(Block.Properties.from(cob));
        slab_concrete = new SlabBlock(Block.Properties.from(concrete));
        slab_cordwood = new SlabBlock(Block.Properties.from(cordwood));
        slab_dry_stone = new SlabBlock(Block.Properties.from(dry_stone));
        slab_gabion0 = new SlabBlock(Block.Properties.from(GRAVEL_GABION));
        slab_gabion1 = new SlabBlock(Block.Properties.from(SAND_GABION));
        slab_gabion2 = new SlabBlock(Block.Properties.from(DIRT_GABION));
        slab_mud = new SlabBlock(Block.Properties.from(mud));
        vertical_oak_slab = new SlabBlock(Block.Properties.from(oak_planks_vert));
        slab_planks_vert1 = new SlabBlock(Block.Properties.from(spruce_planks_vert));
        slab_planks_vert2 = new SlabBlock(Block.Properties.from(birch_planks_vert));
        slab_planks_vert3 = new SlabBlock(Block.Properties.from(jungle_planks_vert));
        slab_planks_vert4 = new SlabBlock(Block.Properties.from(acacia_planks_vert));
        slab_planks_vert5 = new SlabBlock(Block.Properties.from(dark_oak_planks_vert));
        plaster_slab = new SlabBlock(Block.Properties.from(plaster));
        slab_rammed_earth = new SlabBlock(Block.Properties.from(rammed_earth));
        slab_slate = new SlabBlock(Block.Properties.from(slate));
        slab_slate_green = new SlabBlock(Block.Properties.from(block_slate_green));
        slab_slate_purple = new SlabBlock(Block.Properties.from(block_slate_purple));
        slab_slate_slab = new SlabBlock(Block.Properties.from(block_slate_slab));
        slab_slate_slab_green = new SlabBlock(Block.Properties.from(green_slate_slab));
        slab_slate_slab_purple = new SlabBlock(Block.Properties.from(slate_slab_purple));
        slab_slate_shingle = new SlabBlock(Block.Properties.from(slate_shingle));
        slab_slate_shingle_verte = new SlabBlock(Block.Properties.from(block_slate_shingle_verte));
        slab_slate_shingle_purple = new SlabBlock(Block.Properties.from(block_slate_shingle_purple));
        slab_slate_tile = new SlabBlock(Block.Properties.from(block_slate_tile));
        slab_slate_tile_verte = new SlabBlock(Block.Properties.from(block_slate_tile_verte));
        slab_slate_tile_purple = new SlabBlock(Block.Properties.from(block_slate_tile_purple));
        slab_timber_oak = new SlabBlock(Block.Properties.from(block_timber_oak));
        slab_timber_birch = new SlabBlock(Block.Properties.from(block_timber_birch));
        slab_timber_spruce = new SlabBlock(Block.Properties.from(block_timber_spruce));
        slab_timber_jungle = new SlabBlock(Block.Properties.from(block_timber_jungle));
        slab_timber_acacia = new SlabBlock(Block.Properties.from(block_timber_acacia));
        slab_timber_dark_oak = new SlabBlock(Block.Properties.from(block_timber_dark_oak));
        slab_wattle = new SlabBlock(Block.Properties.from(block_wattle));
        slab_wicker = new SlabBlock(Block.Properties.from(block_wicker));
        slab_wood_shingle_oak = new SlabBlock(Block.Properties.from(oak_wood_shingle));
        slab_wood_shingle_spruce = new SlabBlock(Block.Properties.from(oak_wood_shingle));
        slab_wood_shingle_birch = new SlabBlock(Block.Properties.from(oak_wood_shingle));
        slab_wood_shingle_jungle = new SlabBlock(Block.Properties.from(oak_wood_shingle));
        slab_wood_shingle_acacia = new SlabBlock(Block.Properties.from(oak_wood_shingle));
        slab_wood_shingle_dark_oak = new SlabBlock(Block.Properties.from(oak_wood_shingle));

        stair_adobe = new StairsBlock(Block.Properties.from(adobe));
        stair_chalk = new StairsBlock(Block.Properties.from(chalk));
        stair_cinder = new StairsBlock(Block.Properties.from(cinder));
        stair_cob = new StairsBlock(Block.Properties.from(cob);
        stair_concrete = new StairsBlock(Block.Properties.from(concrete);
        stair_cordwood = new StairsBlock(Block.Properties.from(cordwood);
        stair_dry_stone = new StairsBlock(Block.Properties.from(dry_stone);
        stair_gabion0 = new StairsBlock(Block.Properties.from(GRAVEL_GABION);
        stair_gabion1 = new StairsBlock(Block.Properties.from(SAND_GABION);
        stair_gabion2 = new StairsBlock(Block.Properties.from(DIRT_GABION);
        stair_mud = new StairsBlock(Block.Properties.from(mud);
        stair_planks_vert0 = new StairsBlock(Block.Properties.from(adobe);
        stair_planks_vert1 = new StairsBlock(Block.Properties.from(adobe);
        stair_planks_vert2 = new StairsBlock(Block.Properties.from(adobe);
        stair_planks_vert3 = new StairsBlock(Block.Properties.from(adobe);
        stair_planks_vert4 = new StairsBlock(Block.Properties.from(adobe);
        stair_planks_vert5 = new StairsBlock(Block.Properties.from(adobe);
        stair_plaster = new StairsBlock(Block.Properties.from(plaster);
        stair_rammed_earth = new StairsBlock(Block.Properties.from(rammed_earth);
        stair_slate = new StairsBlock(Block.Properties.from(slate);
        stair_slate_green = new StairsBlock(Block.Properties.from(block_slate_green);
        stair_slate_purple = new StairsBlock(Block.Properties.from(block_slate_purple);
        stair_slate_slab = new StairsBlock(Block.Properties.from(block_slate_slab);
        stair_slate_slab_green = new StairsBlock(Block.Properties.from(green_slate_slab);
        stair_slate_slab_purple = new StairsBlock(Block.Properties.from(slate_slab_purple);
        stair_slate_shingle = new StairsBlock(Block.Properties.from(slate_shingle);
        stair_slate_shingle_verte = new StairsBlock(Block.Properties.from(block_slate_shingle_verte);
        stair_slate_shingle_purple = new StairsBlock(Block.Properties.from(block_slate_shingle_purple);
        stair_slate_tile = new StairsBlock(Block.Properties.from(block_slate_tile);
        stair_slate_tile_verte = new StairsBlock(Block.Properties.from(block_slate_tile_verte);
        stair_slate_tile_purple = new StairsBlock(Block.Properties.from(block_slate_tile_purple);
        stair_timber_oak = new StairsBlock(Block.Properties.from(block_timber_oak);
        stair_timber_spruce = new StairsBlock(Block.Properties.from(block_timber_spruce);
        stair_timber_birch = new StairsBlock(block_timber_birch);
        stair_timber_jungle = new StairsBlock(block_timber_jungle);
        stair_timber_acacia = new StairsBlock(block_timber_acacia);
        stair_timber_dark_oak = new StairsBlock(block_timber_dark_oak);
        stair_wattle = new StairsBlock(block_wattle);
        stair_wicker = new StairsBlock(block_wicker);
        stair_wood_shingle_oak = new StairsBlock(oak_wood_shingle);
        stair_wood_shingle_spruce = new StairsBlock(oak_wood_shingle);
        stair_wood_shingle_birch = new StairsBlock(oak_wood_shingle);
        stair_wood_shingle_jungle = new StairsBlock(oak_wood_shingle);
        stair_wood_shingle_acacia = new StairsBlock(oak_wood_shingle);
        stair_wood_shingle_dark_oak = new StairsBlock(oak_wood_shingle);

        wall_adobe = new WallBlock(adobe);
        wall_chalk = new WallBlock(chalk);
        wall_cinder = new WallBlock(cinder);
        wall_cob = new WallBlock(cob);
        wall_concrete = new WallBlock(concrete);
        wall_cordwood = new WallBlock(cordwood);
        wall_dry_stone = new WallBlock(dry_stone);
        wall_gabion0 = new WallBlock(GRAVEL_GABION);
        wall_gabion1 = new WallBlock(SAND_GABION);
        wall_gabion2 = new WallBlock(DIRT_GABION);
        wall_mud = new WallBlock(mud);
        wall_plaster = new WallBlock(plaster);
        wall_rammed_earth = new WallBlock(rammed_earth);
        wall_slate = new WallBlock(slate);
        wall_slate_green = new WallBlock(block_slate_green);
        wall_slate_purple = new WallBlock(block_slate_purple);
        wall_slate_slab = new WallBlock(block_slate_slab);
        wall_slate_slab_green = new WallBlock(green_slate_slab);
        wall_slate_slab_purple = new WallBlock(slate_slab_purple);
        wall_slate_shingle = new WallBlock(slate_shingle);
        wall_slate_shingle_verte = new WallBlock(block_slate_shingle_verte);
        wall_slate_shingle_purple = new WallBlock(block_slate_shingle_purple);
        wall_slate_tile = new WallBlock(block_slate_tile);
        wall_slate_tile_verte = new WallBlock(block_slate_tile_verte);
        wall_slate_tile_purple = new WallBlock(block_slate_tile_purple);
        wall_timber_oak = new WallBlock(block_timber_oak);
        wall_timber_spruce = new WallBlock(block_timber_spruce);
        wall_timber_birch = new WallBlock(block_timber_birch);
        wall_timber_jungle = new WallBlock(block_timber_jungle);
        wall_timber_acacia = new WallBlock(block_timber_acacia);
        wall_timber_dark_oak = new WallBlock(block_timber_dark_oak);
        wall_wattle = new WallBlock(block_wattle);
        wall_wicker = new WallBlock(block_wicker);
        wall_wood_shingle_oak = new WallBlock(oak_wood_shingle);
        wall_wood_shingle_spruce = new WallBlock(oak_wood_shingle);
        wall_wood_shingle_birch = new WallBlock(oak_wood_shingle);
        wall_wood_shingle_jungle = new WallBlock(oak_wood_shingle);
        wall_wood_shingle_acacia = new WallBlock(oak_wood_shingle);
        wall_wood_shingle_dark_oak = new WallBlock(oak_wood_shingle);

        //  QUARK COMPAT    //

        block_reed = new RotatedPillarBlock(Material.LEAVES, SoundType.CLOTH, 0.8F, 1.0F);
        block_thatch = new RotatedPillarBlock(Material.LEAVES, SoundType.CLOTH, 0.8F, 1.0F);

        slab_reed = new SlabBlock(Block.Properties.from(block_reed));
        doubleslab_reed = new SlabBlock(Block.Properties.from(slab_reed));

        slab_thatch = new SlabBlock(Block.Properties.from(block_thatch));
        doubleslab_thatch = new SlabBlock(Block.Properties.from(slab_thatch));


        stair_reed = new StairsBlock(block_reed);
        stair_thatch = new StairsBlock(block_thatch);

        wall_reed = new WallBlock(block_reed);
        wall_thatch = new WallBlock(block_thatch);
    }

    public static void initItemBlocks(RegistryEvent.Register<Item> event) {
        IForgeRegistry<Item> r = event.getRegistry();
        r.register(itemblock(adobe));
        r.register(itemblock(chalk));
        r.register(itemblock(cinder));
        r.register(itemblock(cob));
        r.register(itemblock(concrete));
        r.register(itemblock(cordwood));
        r.register(itemblock(dry_stone));
        r.register(itemblock(GRAVEL_GABION));
        r.register(itemblock(SAND_GABION));
        r.register(itemblock(DIRT_GABION));
        r.register(itemblock(mud));

            r.register(new BlockItemPlanksVert(oak_planks_vert).setRegistryName(oak_planks_vert.getRegistryName()));

        r.register(itemblock(plaster));
        r.register(itemblock(rammed_earth));
        r.register(itemblock(slate));
        r.register(itemblock(block_slate_green));
        r.register(itemblock(block_slate_purple));
        r.register(itemblock(block_slate_slab));
        r.register(itemblock(green_slate_slab));
        r.register(itemblock(slate_slab_purple));
        r.register(itemblock(slate_shingle));
        r.register(itemblock(block_slate_shingle_verte));
        r.register(itemblock(block_slate_shingle_purple));
        r.register(itemblock(block_slate_tile));
        r.register(itemblock(block_slate_tile_verte));
        r.register(itemblock(block_slate_tile_purple));
        r.register(itemblock(block_timber_oak));
        r.register(itemblock(block_timber_birch));
        r.register(itemblock(block_timber_spruce));
        r.register(itemblock(block_timber_jungle));
        r.register(itemblock(block_timber_acacia));
        r.register(itemblock(block_timber_dark_oak));
        r.register(itemblock(block_wattle));
        r.register(itemblock(block_wicker));
        r.register(new BlockItemWoodShingle(oak_wood_shingle).setRegistryName(oak_wood_shingle.getRegistryName()));

        r.register(itemblock(fence_planks_vert0));
        r.register(itemblock(fence_planks_vert1));
        r.register(itemblock(fence_planks_vert2));
        r.register(itemblock(fence_planks_vert3));
        r.register(itemblock(fence_planks_vert4));
        r.register(itemblock(fence_planks_vert5));

        ItemRegistry.itemslab_adobe = new BlockItem(r, slab_adobe, doubleslab_adobe);
        ItemRegistry.itemslab_chalk = new BlockItem(r, slab_chalk, doubleslab_chalk);
        ItemRegistry.itemslab_cinder = new BlockItem(r, slab_cinder, doubleslab_cinder);
        ItemRegistry.itemslab_cob = new BlockItem(r, slab_cob, doubleslab_cob);
        ItemRegistry.itemslab_concrete = new BlockItem(r, slab_concrete, doubleslab_concrete);
        ItemRegistry.itemslab_cordwood = new BlockItem(r, slab_cordwood, doubleslab_cordwood);
        ItemRegistry.itemslab_dry_stone = new BlockItem(r, slab_dry_stone, doubleslab_dry_stone);
        ItemRegistry.itemslab_gabion0 = new BlockItem(r, slab_gabion0, doubleslab_gabion0);
        ItemRegistry.itemslab_gabion1 = new BlockItem(r, slab_gabion1, doubleslab_gabion1);
        ItemRegistry.itemslab_gabion2 = new BlockItem(r, slab_gabion2, doubleslab_gabion2);
        ItemRegistry.itemslab_mud = new BlockItem(r, slab_mud, doubleslab_mud);
        ItemRegistry.itemslab_planks_vert0 = new BlockItem(r, vertical_oak_slab, doubleslab_planks_vert0);
        ItemRegistry.itemslab_planks_vert1 = new BlockItem(r, slab_planks_vert1, doubleslab_planks_vert1);
        ItemRegistry.itemslab_planks_vert2 = new BlockItem(r, slab_planks_vert2, doubleslab_planks_vert2);
        ItemRegistry.itemslab_planks_vert3 = new BlockItem(r, slab_planks_vert3, doubleslab_planks_vert3);
        ItemRegistry.itemslab_planks_vert4 = new BlockItem(r, slab_planks_vert4, doubleslab_planks_vert4);
        ItemRegistry.itemslab_planks_vert5 = new BlockItem(r, slab_planks_vert5, doubleslab_planks_vert5);
        ItemRegistry.itemslab_plaster = new BlockItem(r, plaster_slab, doubleslab_plaster);
        ItemRegistry.itemslab_rammed_earth = new BlockItem(r, slab_rammed_earth, doubleslab_rammed_earth);
        ItemRegistry.itemslab_slate = new BlockItem(r, slab_slate, doubleslab_slate);
        ItemRegistry.itemslab_slate_green = new BlockItem(r, slab_slate_green, doubleslab_slate_green);
        ItemRegistry.itemslab_slate_purple = new BlockItem(r, slab_slate_purple, doubleslab_slate_purple);
        ItemRegistry.itemslab_slate_slab = new BlockItem(r, slab_slate_slab, doubleslab_slate_slab);
        ItemRegistry.itemslab_slate_slab_green = new BlockItem(r, slab_slate_slab_green, doubleslab_slate_slab_green);
        ItemRegistry.itemslab_slate_slab_purple = new BlockItem(r, slab_slate_slab_purple, doubleslab_slate_slab_purple);
        ItemRegistry.itemslab_slate_shingle = new BlockItem(r, slab_slate_shingle, doubleslab_slate_shingle);
        ItemRegistry.itemslab_slate_shingle_verte = new BlockItem(r, slab_slate_shingle_verte, doubleslab_slate_shingle_verte);
        ItemRegistry.itemslab_slate_shingle_purple = new BlockItem(r, slab_slate_shingle_purple, doubleslab_slate_shingle_purple);
        ItemRegistry.itemslab_slate_tile = new BlockItem(r, slab_slate_tile, doubleslab_slate_tile);
        ItemRegistry.itemslab_slate_tile_verte = new BlockItem(r, slab_slate_tile_verte, doubleslab_slate_tile_verte);
        ItemRegistry.itemslab_slate_tile_purple = new BlockItem(r, slab_slate_tile_purple, doubleslab_slate_tile_purple);
        ItemRegistry.itemslab_timber_oak = new BlockItem(r, slab_timber_oak, doubleslab_timber_oak);
        ItemRegistry.itemslab_timber_birch = new BlockItem(r, slab_timber_birch, doubleslab_timber_birch);
        ItemRegistry.itemslab_timber_spruce = new BlockItem(r, slab_timber_spruce, doubleslab_timber_spruce);
        ItemRegistry.itemslab_timber_jungle = new BlockItem(r, slab_timber_jungle, doubleslab_timber_jungle);
        ItemRegistry.itemslab_timber_acacia = new BlockItem(r, slab_timber_acacia, doubleslab_timber_acacia);
        ItemRegistry.itemslab_timber_dark_oak = new BlockItem(r, slab_timber_dark_oak, doubleslab_timber_dark_oak);
        ItemRegistry.itemslab_wattle = new BlockItem(r, slab_wattle, doubleslab_wattle);
        ItemRegistry.itemslab_wicker = new BlockItem(r, slab_wicker, doubleslab_wicker);
        ItemRegistry.itemslab_wood_shingle_oak = new BlockItem(r, slab_wood_shingle_oak, doubleslab_wood_shingle_oak);
        ItemRegistry.itemslab_wood_shingle_spruce = new BlockItem(r, slab_wood_shingle_spruce, doubleslab_wood_shingle_spruce);
        ItemRegistry.itemslab_wood_shingle_birch = new BlockItem(r, slab_wood_shingle_birch, doubleslab_wood_shingle_birch);
        ItemRegistry.itemslab_wood_shingle_jungle = new BlockItem(r, slab_wood_shingle_jungle, doubleslab_wood_shingle_jungle);
        ItemRegistry.itemslab_wood_shingle_acacia = new BlockItem(r, slab_wood_shingle_acacia, doubleslab_wood_shingle_acacia);
        ItemRegistry.itemslab_wood_shingle_dark_oak = new BlockItem(r, slab_wood_shingle_dark_oak, doubleslab_wood_shingle_dark_oak);

        r.register(itemblock(stair_adobe));
        r.register(itemblock(stair_chalk));
        r.register(itemblock(stair_cinder));
        r.register(itemblock(stair_cob));
        r.register(itemblock(stair_concrete));
        r.register(itemblock(stair_cordwood));
        r.register(itemblock(stair_dry_stone));
        r.register(itemblock(stair_gabion0));
        r.register(itemblock(stair_gabion1));
        r.register(itemblock(stair_gabion2));
        r.register(itemblock(stair_mud));
        r.register(itemblock(stair_planks_vert0));
        r.register(itemblock(stair_planks_vert1));
        r.register(itemblock(stair_planks_vert2));
        r.register(itemblock(stair_planks_vert3));
        r.register(itemblock(stair_planks_vert4));
        r.register(itemblock(stair_planks_vert5));
        r.register(itemblock(stair_plaster));
        r.register(itemblock(stair_rammed_earth));
        r.register(itemblock(stair_slate));
        r.register(itemblock(stair_slate_green));
        r.register(itemblock(stair_slate_purple));
        r.register(itemblock(stair_slate_slab));
        r.register(itemblock(stair_slate_slab_green));
        r.register(itemblock(stair_slate_slab_purple));
        r.register(itemblock(stair_slate_shingle));
        r.register(itemblock(stair_slate_shingle_verte));
        r.register(itemblock(stair_slate_shingle_purple));
        r.register(itemblock(stair_slate_tile));
        r.register(itemblock(stair_slate_tile_verte));
        r.register(itemblock(stair_slate_tile_purple));
        r.register(itemblock(stair_timber_oak));
        r.register(itemblock(stair_timber_birch));
        r.register(itemblock(stair_timber_spruce));
        r.register(itemblock(stair_timber_jungle));
        r.register(itemblock(stair_timber_acacia));
        r.register(itemblock(stair_timber_dark_oak));
        r.register(itemblock(stair_wattle));
        r.register(itemblock(stair_wicker));
        r.register(itemblock(stair_wood_shingle_oak));
        r.register(itemblock(stair_wood_shingle_spruce));
        r.register(itemblock(stair_wood_shingle_birch));
        r.register(itemblock(stair_wood_shingle_jungle));
        r.register(itemblock(stair_wood_shingle_acacia));
        r.register(itemblock(stair_wood_shingle_dark_oak));

        r.register(itemblock(wall_adobe));
        r.register(itemblock(wall_chalk));
        r.register(itemblock(wall_cinder));
        r.register(itemblock(wall_cob));
        r.register(itemblock(wall_concrete));
        r.register(itemblock(wall_cordwood));
        r.register(itemblock(wall_dry_stone));
        r.register(itemblock(wall_gabion0));
        r.register(itemblock(wall_gabion1));
        r.register(itemblock(wall_gabion2));
        r.register(itemblock(wall_mud));
        r.register(itemblock(wall_plaster));
        r.register(itemblock(wall_rammed_earth));
        r.register(itemblock(wall_slate));
        r.register(itemblock(wall_slate_green));
        r.register(itemblock(wall_slate_purple));
        r.register(itemblock(wall_slate_slab));
        r.register(itemblock(wall_slate_slab_green));
        r.register(itemblock(wall_slate_slab_purple));
        r.register(itemblock(wall_slate_shingle));
        r.register(itemblock(wall_slate_shingle_verte));
        r.register(itemblock(wall_slate_shingle_purple));
        r.register(itemblock(wall_slate_tile));
        r.register(itemblock(wall_slate_tile_verte));
        r.register(itemblock(wall_slate_tile_purple));
        r.register(itemblock(wall_timber_oak));
        r.register(itemblock(wall_timber_birch));
        r.register(itemblock(wall_timber_spruce));
        r.register(itemblock(wall_timber_jungle));
        r.register(itemblock(wall_timber_acacia));
        r.register(itemblock(wall_timber_dark_oak));
        r.register(itemblock(wall_wattle));
        r.register(itemblock(wall_wicker));
        r.register(itemblock(wall_wood_shingle_oak));
        r.register(itemblock(wall_wood_shingle_spruce));
        r.register(itemblock(wall_wood_shingle_birch));
        r.register(itemblock(wall_wood_shingle_jungle));
        r.register(itemblock(wall_wood_shingle_acacia));
        r.register(itemblock(wall_wood_shingle_dark_oak));
            r.register(itemblock(block_reed));
            r.register(itemblock(block_thatch));
            ItemRegistry.itemslab_reed = new BlockItem(r, slab_reed, doubleslab_reed);
            ItemRegistry.itemslab_thatch = new BlockItem(r, slab_thatch, doubleslab_thatch);
            r.register(itemblock(stair_reed));
            r.register(itemblock(stair_thatch));
            r.register(itemblock(wall_reed));
            r.register(itemblock(wall_thatch));
    }

    private static final List<Block> cache = new ArrayList<>();

    public static List<Block> getAllBlocks() {
        if (cache.isEmpty()) {
            Field[] fields = BlockRegistry.class.getFields();

            for (Field field : fields) {
                try {
                    if (field.get(null) instanceof Block) {
                        cache.add((Block) field.get(null));
                    }
                } catch (IllegalAccessException e) {
                    e.printStackTrace();
                }
            }
        }
        return cache;
    }

    private static Item itemblock(Block block) {
        return new BlockItem(block).setRegistryName(block.getRegistryName());
    }
}